<?php echo $header; ?><?php echo $column_left; ?>
<div id="content"><div class="page-header"><div class="container-fluid"><div class="pull-right"><button type="submit" form="form-mochipay" class="btn btn-primary"><i class="fa fa-save"></i></button><a href="<?php echo $cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a></div><h1><?php echo $heading_title; ?></h1></div></div>
<div class="container-fluid"><?php if ($error_warning) { ?><div class="alert alert-danger"><?php echo $error_warning; ?></div><?php } ?>
<div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title"><?php echo $text_edit; ?></h3></div><div class="panel-body"><p><strong>Callback URL:</strong> <code><?php echo $callback_url; ?></code></p>
<form action="<?php echo $action; ?>" method="post" id="form-mochipay" class="form-horizontal">
<?php $fields = array('title','api_url','api_key','api_secret','sort_order'); foreach ($fields as $field) { ?><div class="form-group"><label class="col-sm-2 control-label"><?php echo ${'entry_' . $field}; ?></label><div class="col-sm-10"><input type="<?php echo $field == 'api_secret' ? 'password' : 'text'; ?>" name="mochipay_<?php echo $field; ?>" value="<?php echo htmlspecialchars(${'mochipay_' . $field}, ENT_QUOTES, 'UTF-8'); ?>" class="form-control" /><?php if ($field == 'payment_methods') { ?><p class="help-block"><?php echo $help_payment_methods; ?></p><?php } ?></div></div><?php } ?>
<div class="form-group"><label class="col-sm-2 control-label"><?php echo $entry_unique_direction; ?></label><div class="col-sm-10"><select name="mochipay_unique_direction" class="form-control"><option value="UP"<?php echo $mochipay_unique_direction == 'UP' ? ' selected' : ''; ?>>UP</option><option value="DOWN"<?php echo $mochipay_unique_direction == 'DOWN' ? ' selected' : ''; ?>>DOWN</option></select></div></div>
<?php foreach (array('pending','paid') as $type) { ?><div class="form-group"><label class="col-sm-2 control-label"><?php echo ${'entry_' . $type . '_status'}; ?></label><div class="col-sm-10"><select name="mochipay_<?php echo $type; ?>_status_id" class="form-control"><?php foreach ($order_statuses as $status) { ?><option value="<?php echo $status['order_status_id']; ?>"<?php echo ${'mochipay_' . $type . '_status_id'} == $status['order_status_id'] ? ' selected' : ''; ?>><?php echo $status['name']; ?></option><?php } ?></select></div></div><?php } ?>
<div class="form-group"><label class="col-sm-2 control-label"><?php echo $entry_status; ?></label><div class="col-sm-10"><select name="mochipay_status" class="form-control"><option value="1"<?php echo $mochipay_status ? ' selected' : ''; ?>><?php echo $text_enabled; ?></option><option value="0"<?php echo !$mochipay_status ? ' selected' : ''; ?>><?php echo $text_disabled; ?></option></select></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Payment Interface</label><div class="col-sm-10"><select name="mochipay_checkout_mode" class="form-control"><option value="HPP">HPP — Redirect to MochiPay</option><option value="ON_SITE"<?php echo $mochipay_checkout_mode == 'ON_SITE' ? ' selected' : ''; ?>>On-site — Payment dialog</option></select></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Customer Payment Choices</label><div class="col-sm-10"><input type="hidden" name="mochipay_payment_methods[]" value="" /><?php foreach($method_options as $code=>$label){ ?><label style="display:block"><input type="checkbox" name="mochipay_payment_methods[]" value="<?php echo $code; ?>"<?php echo in_array($code,$selected_methods,true)?' checked':''; ?>> <?php echo $label; ?></label><?php } ?></div></div></form></div></div></div></div><?php echo $footer; ?>
